### ISSUE TITLE
라이선스 문제

### ISSUE THREAD

**Issue by cog25** [covid-hcs/hcs-python#1]
GPL 하에 배포되었으니, 기존 개발자를 표시해야 하지 않을까요?

**Comment by lhwdev** [comment]
![image](https://user-images.githubusercontent.com/36781325/141328930-f15f1319-7a88-487b-bc14-58e5b9f1bec1.png)
이걸로는 안되려나요

**Comment by cog25** [comment]
어 못봤어요

**Comment by lhwdev** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by scottjsh** [comment]
ㅋㅋㅋㅋㅋ
