### ISSUE TITLE
UI 버전 관련 호환성 문제

### ISSUE THREAD

**Issue by lhwdev** [covid-hcs/hcs-python#6]
지금 /registerServey의 clientVersion 항목 (웹사이트의 UI ver. 버전이랑 일치) 이 올라갈 때마다 매번 코드를 새롭게 올려야 하는지 의문이네요. 물론 버전이 올라가면서 호환성이 깨질 수도 있지만, 대부분 안그러니 자동으로 버전을 긁어오는 것도 나쁘지 않을 거 같고요.
긁어오는 방법은 걍 간단합니다. https://hcs.eduro.go.kr 에서 app.(해시).js의 경로를 찾아서 그 파일에서 `window.PACKAGE_VERSION = "..."`이란 부분을 찾으면 되긴 해요. 근데.. 이게 맞나?

**Comment by lhwdev** [comment]
어디 ui 버전만 있는 api 없나.. 매번 app.js를 받는 거는 오버헤드가 클 거 같네요.

**Comment by scottjsh** [comment]
```
res = requests.get("https://hcs.eduro.go.kr/")
f = open("../version.txt","w+",encoding="utf-8")
f.write(res.headers['X-Client-Version'])
f.close()
print(f"clientVersion: {res.headers['X-Client-Version']}")
```

음 파이썬 기준임니다
그리고 자가진단 봇 기준
저는 cogs/tasks.py에 넣었습니다

**Comment by lhwdev** [comment]
안그래도 최근에 X-Client-Version을 알게 됐습니다..!
왜 몰랐을까요 바로 바꿀게요

**Comment by lhwdev** [comment]
그런데 아직 덜 고쳤습니다. 오류 나네요 저런

**Comment by scottjsh** [comment]
음?

**Comment by lhwdev** [comment]
아 지금은 고친 상태입니다
